name: condevra
channels:
  - conda-forge
  - defaults
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libmpdec=4.0.0
  - libnsl=2.0.1
  - libsqlite=3.48.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=25.0
  - python=3.10.0
  - python_abi=3.10
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.48.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - pip:
      - absl-py==1.4.0
      - ai-edge-litert==1.0.1
      - array-record==0.6.0
      - arviz==0.20.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==25.1.0
      - bleach==6.2.0
      - cachetools==5.5.1
      - cattrs==24.1.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cmdstanpy==1.2.5
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==0.29.37
      - decorator==5.1.1
      - dm-tree==0.1.9
      - docstring-parser==0.16
      - ephem==4.1.6
      - etils==1.11.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - filelock==3.17.0
      - flatbuffers==25.1.24
      - fonttools==4.55.8
      - fsspec==2025.2.0
      - gast==0.4.0
      - gin-config==0.5.0
      - google-api-core==2.24.1
      - google-api-python-client==2.160.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.66.0
      - grpcio==1.70.0
      - h5netcdf==1.5.0
      - h5py==3.12.1
      - httplib2==0.22.0
      - idna==3.10
      - immutabledict==4.2.1
      - importlib-resources==6.5.2
      - ipython==6.0.0
      - jax==0.4.38
      - jaxlib==0.4.38
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - kaggle==1.6.17
      - keras==2.12.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.4.2
      - numpy==1.24.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.0
      - orbit-ml==1.1.4.4
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==4.3.6
      - portalocker==3.1.1
      - promise==2.3
      - prompt-toolkit==1.0.18
      - proto-plus==1.26.0
      - protobuf==3.20.3
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycocotools==2.0.8
      - pyephem==9.99
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.17.0
      - pyqt6==6.8.0
      - pyqt6-qt6==6.8.1
      - pyqt6-sip==13.10.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytz==2025.1
      - pyyaml==5.3.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-cache==1.2.1
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rsa==4.9
      - sacrebleu==2.5.1
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - seqeval==1.2.2
      - simple-parsing==0.1.7
      - simplegeneric==0.8.1
      - six==1.17.0
      - stack-data==0.6.3
      - stanio==0.5.1
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.2
      - tensorflow==2.12.1
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.7
      - tensorflow-estimator==2.12.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.16.1
      - tensorflow-model-optimization==0.8.0
      - tensorflow-text==2.12.1
      - termcolor==2.5.0
      - text-unidecode==1.3
      - tf-keras==2.15.0
      - tf-models-official==2.12.0
      - tf-slim==1.1.0
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - torch==2.6.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.2.0
      - typeguard==2.13.3
      - typing-extensions==4.5.0
      - tzdata==2025.1
      - uritemplate==4.1.1
      - url-normalize==1.4.3
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==1.14.1
      - xarray==2025.1.2
      - xarray-einstats==0.8.0
      - zipp==3.21.0
